// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Svm.Genesis.Outputs
{

    [OutputType]
    public sealed class PrimorialEntry
    {
        public readonly string Lamports;
        public readonly string Pubkey;

        [OutputConstructor]
        private PrimorialEntry(
            string lamports,

            string pubkey)
        {
            Lamports = lamports;
            Pubkey = pubkey;
        }
    }
}
