#!/usr/bin/env bash

setup::mac() {
	brew install golangci-lint shfmt shellcheck
}

setup::linux() {
        sudo curl -o /usr/local/bin/opsh https://github.com/alexanderguy/opsh/releases/latest/download/opsh
        sudo chmod a+rx /usr/local/bin/opsh
    
	sudo snap install --classic golangci-lint
	sudo apt-get update
	sudo DEBIAN_FRONTEND=noninteractive apt-get install -qy shfmt shellcheck
}

if [ "$(uname)" = "Darwin" ]; then
	setup::mac
else
	setup::linux
fi
