// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package solana

import (
	"context"
	"reflect"

	"github.com/abklabs/svmkit/sdk/go/svmkit/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type GenesisFlags struct {
	ClusterType                *string `pulumi:"clusterType"`
	FaucetLamports             *string `pulumi:"faucetLamports"`
	FaucetPubkey               string  `pulumi:"faucetPubkey"`
	IdentityPubkey             string  `pulumi:"identityPubkey"`
	Inflation                  *string `pulumi:"inflation"`
	LamportsPerByteYear        *string `pulumi:"lamportsPerByteYear"`
	LedgerPath                 string  `pulumi:"ledgerPath"`
	SlotPerEpoch               *string `pulumi:"slotPerEpoch"`
	StakePubkey                string  `pulumi:"stakePubkey"`
	TargetLamportsPerSignature *string `pulumi:"targetLamportsPerSignature"`
	VotePubkey                 string  `pulumi:"votePubkey"`
}

// GenesisFlagsInput is an input type that accepts GenesisFlagsArgs and GenesisFlagsOutput values.
// You can construct a concrete instance of `GenesisFlagsInput` via:
//
//	GenesisFlagsArgs{...}
type GenesisFlagsInput interface {
	pulumi.Input

	ToGenesisFlagsOutput() GenesisFlagsOutput
	ToGenesisFlagsOutputWithContext(context.Context) GenesisFlagsOutput
}

type GenesisFlagsArgs struct {
	ClusterType                pulumi.StringPtrInput `pulumi:"clusterType"`
	FaucetLamports             pulumi.StringPtrInput `pulumi:"faucetLamports"`
	FaucetPubkey               pulumi.StringInput    `pulumi:"faucetPubkey"`
	IdentityPubkey             pulumi.StringInput    `pulumi:"identityPubkey"`
	Inflation                  pulumi.StringPtrInput `pulumi:"inflation"`
	LamportsPerByteYear        pulumi.StringPtrInput `pulumi:"lamportsPerByteYear"`
	LedgerPath                 pulumi.StringInput    `pulumi:"ledgerPath"`
	SlotPerEpoch               pulumi.StringPtrInput `pulumi:"slotPerEpoch"`
	StakePubkey                pulumi.StringInput    `pulumi:"stakePubkey"`
	TargetLamportsPerSignature pulumi.StringPtrInput `pulumi:"targetLamportsPerSignature"`
	VotePubkey                 pulumi.StringInput    `pulumi:"votePubkey"`
}

func (GenesisFlagsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GenesisFlags)(nil)).Elem()
}

func (i GenesisFlagsArgs) ToGenesisFlagsOutput() GenesisFlagsOutput {
	return i.ToGenesisFlagsOutputWithContext(context.Background())
}

func (i GenesisFlagsArgs) ToGenesisFlagsOutputWithContext(ctx context.Context) GenesisFlagsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GenesisFlagsOutput)
}

type GenesisFlagsOutput struct{ *pulumi.OutputState }

func (GenesisFlagsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GenesisFlags)(nil)).Elem()
}

func (o GenesisFlagsOutput) ToGenesisFlagsOutput() GenesisFlagsOutput {
	return o
}

func (o GenesisFlagsOutput) ToGenesisFlagsOutputWithContext(ctx context.Context) GenesisFlagsOutput {
	return o
}

func (o GenesisFlagsOutput) ClusterType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GenesisFlags) *string { return v.ClusterType }).(pulumi.StringPtrOutput)
}

func (o GenesisFlagsOutput) FaucetLamports() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GenesisFlags) *string { return v.FaucetLamports }).(pulumi.StringPtrOutput)
}

func (o GenesisFlagsOutput) FaucetPubkey() pulumi.StringOutput {
	return o.ApplyT(func(v GenesisFlags) string { return v.FaucetPubkey }).(pulumi.StringOutput)
}

func (o GenesisFlagsOutput) IdentityPubkey() pulumi.StringOutput {
	return o.ApplyT(func(v GenesisFlags) string { return v.IdentityPubkey }).(pulumi.StringOutput)
}

func (o GenesisFlagsOutput) Inflation() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GenesisFlags) *string { return v.Inflation }).(pulumi.StringPtrOutput)
}

func (o GenesisFlagsOutput) LamportsPerByteYear() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GenesisFlags) *string { return v.LamportsPerByteYear }).(pulumi.StringPtrOutput)
}

func (o GenesisFlagsOutput) LedgerPath() pulumi.StringOutput {
	return o.ApplyT(func(v GenesisFlags) string { return v.LedgerPath }).(pulumi.StringOutput)
}

func (o GenesisFlagsOutput) SlotPerEpoch() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GenesisFlags) *string { return v.SlotPerEpoch }).(pulumi.StringPtrOutput)
}

func (o GenesisFlagsOutput) StakePubkey() pulumi.StringOutput {
	return o.ApplyT(func(v GenesisFlags) string { return v.StakePubkey }).(pulumi.StringOutput)
}

func (o GenesisFlagsOutput) TargetLamportsPerSignature() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GenesisFlags) *string { return v.TargetLamportsPerSignature }).(pulumi.StringPtrOutput)
}

func (o GenesisFlagsOutput) VotePubkey() pulumi.StringOutput {
	return o.ApplyT(func(v GenesisFlags) string { return v.VotePubkey }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GenesisFlagsInput)(nil)).Elem(), GenesisFlagsArgs{})
	pulumi.RegisterOutputType(GenesisFlagsOutput{})
}
