// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Svmkit.Module.Inputs
{

    public sealed class PrimorialEntryArgs : global::Pulumi.ResourceArgs
    {
        [Input("lamports", required: true)]
        public Input<string> Lamports { get; set; } = null!;

        [Input("pubkey", required: true)]
        public Input<string> Pubkey { get; set; } = null!;

        public PrimorialEntryArgs()
        {
        }
        public static new PrimorialEntryArgs Empty => new PrimorialEntryArgs();
    }
}
