# generic.defaults.toml

[params]
# List of ports and/or services to allow through the firewall.
# If this is empty or omitted, all ports are denied (except those allowed by default ufw rules).
allowPorts = [
  "ssh",          # Allow SSH
  "53"            # Allow DNS (TCP+UDP)
 ]
