// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { SolanaArgs } from "./solana";
export type Solana = import("./solana").Solana;
export const Solana: typeof import("./solana").Solana = null as any;
utilities.lazyLoad(exports, ["Solana"], () => require("./solana"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "svmkit:genesis:Solana":
                return new Solana(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("svmkit", "genesis", _module)
