# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_svm.agave as __agave
    agave = __agave
    import pulumi_svm.svm as __svm
    svm = __svm
else:
    agave = _utilities.lazy_import('pulumi_svm.agave')
    svm = _utilities.lazy_import('pulumi_svm.svm')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "svm",
  "mod": "svm",
  "fqn": "pulumi_svm.svm",
  "classes": {
   "svm:svm:KeyPair": "KeyPair",
   "svm:svm:Validator": "Validator"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "svm",
  "token": "pulumi:providers:svm",
  "fqn": "pulumi_svm",
  "class": "Provider"
 }
]
"""
)
