# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .key_pair import *
from .provider import *
from .validator import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_svm.agave as __agave
    agave = __agave
    import pulumi_svm.ssh as __ssh
    ssh = __ssh
else:
    agave = _utilities.lazy_import('pulumi_svm.agave')
    ssh = _utilities.lazy_import('pulumi_svm.ssh')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "svm",
  "mod": "index",
  "fqn": "pulumi_svm",
  "classes": {
   "svm:index:KeyPair": "KeyPair",
   "svm:index:Validator": "Validator"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "svm",
  "token": "pulumi:providers:svm",
  "fqn": "pulumi_svm",
  "class": "Provider"
 }
]
"""
)
