// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Svm.Solana.Outputs
{

    [OutputType]
    public sealed class GenesisFlags
    {
        public readonly string? ClusterType;
        public readonly string? FaucetLamports;
        public readonly string FaucetPubkey;
        public readonly string IdentityPubkey;
        public readonly string? Inflation;
        public readonly string? LamportsPerByteYear;
        public readonly string LedgerPath;
        public readonly string? SlotPerEpoch;
        public readonly string StakePubkey;
        public readonly string? TargetLamportsPerSignature;
        public readonly string VotePubkey;

        [OutputConstructor]
        private GenesisFlags(
            string? clusterType,

            string? faucetLamports,

            string faucetPubkey,

            string identityPubkey,

            string? inflation,

            string? lamportsPerByteYear,

            string ledgerPath,

            string? slotPerEpoch,

            string stakePubkey,

            string? targetLamportsPerSignature,

            string votePubkey)
        {
            ClusterType = clusterType;
            FaucetLamports = faucetLamports;
            FaucetPubkey = faucetPubkey;
            IdentityPubkey = identityPubkey;
            Inflation = inflation;
            LamportsPerByteYear = lamportsPerByteYear;
            LedgerPath = ledgerPath;
            SlotPerEpoch = slotPerEpoch;
            StakePubkey = stakePubkey;
            TargetLamportsPerSignature = targetLamportsPerSignature;
            VotePubkey = votePubkey;
        }
    }
}
