// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class Agave extends pulumi.CustomResource {
    /**
     * Get an existing Agave resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Agave {
        return new Agave(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'svmkit:validator:Agave';

    /**
     * Returns true if the given object is an instance of Agave.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Agave {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Agave.__pulumiType;
    }

    public readonly connection!: pulumi.Output<outputs.ssh.Connection>;
    public readonly flags!: pulumi.Output<outputs.agave.Flags>;
    public readonly keyPairs!: pulumi.Output<outputs.agave.KeyPairs>;

    /**
     * Create a Agave resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AgaveArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.connection === undefined) && !opts.urn) {
                throw new Error("Missing required property 'connection'");
            }
            if ((!args || args.flags === undefined) && !opts.urn) {
                throw new Error("Missing required property 'flags'");
            }
            if ((!args || args.keyPairs === undefined) && !opts.urn) {
                throw new Error("Missing required property 'keyPairs'");
            }
            resourceInputs["connection"] = args ? (args.connection ? pulumi.output(args.connection).apply(inputs.ssh.connectionArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["flags"] = args ? args.flags : undefined;
            resourceInputs["keyPairs"] = args?.keyPairs ? pulumi.secret(args.keyPairs) : undefined;
        } else {
            resourceInputs["connection"] = undefined /*out*/;
            resourceInputs["flags"] = undefined /*out*/;
            resourceInputs["keyPairs"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["keyPairs"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Agave.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Agave resource.
 */
export interface AgaveArgs {
    connection: pulumi.Input<inputs.ssh.ConnectionArgs>;
    flags: pulumi.Input<inputs.agave.FlagsArgs>;
    keyPairs: pulumi.Input<inputs.agave.KeyPairsArgs>;
}
