#!/usr/bin/env bash

set -euo pipefail
SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. "$SCRIPTDIR/lib.bash"

ARCHIVE_FNAME=$1 ; shift

keypair::write IDENTITY_KEYPAIR validator-keypair.json
keypair::write VOTEACCOUNT_KEYPAIR vote-account-keypair.json
keypair::write STAKEACCOUNT_KEYPAIR stake-keypair.json

env::kv VALIDATOR_VARIANT VALIDATOR_FLAGS > "env"

(cd "$SCRIPTDIR/.." && tar cvzf "$ARCHIVE_FNAME" $(basename "$SCRIPTDIR"))
