#!/usr/bin/env bash
set -euo pipefail
SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. "$SCRIPTDIR/lib.bash"

if [[ $# -lt 2 ]] ; then
   log::fatal "usage: $0 stepprefix stepfile"
fi

STEPPREFIX=$1 ; shift
STEPFILE=$1 ; shift

[[ -f $STEPFILE ]] || log::fatal "step file '$STEPFILE' doesn't exist!"

# shellcheck disable=SC1090
. "$STEPFILE"
step::run "$STEPPREFIX::" "$@"
