// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace agave {
    export interface ValidatorFlags {
        blockProductionMethod: string;
        dynamicPortRange: string;
        entryPoint: string[];
        expectedGenesisHash: string;
        fullRpcAPI: boolean;
        fullSnapshotIntervalSlots: number;
        gossipPort: number;
        knownValidator: string[];
        limitLedgerSize: number;
        noVoting: boolean;
        noWaitForVoteToStartLeader: boolean;
        onlyKnownRPC: boolean;
        paths: outputs.agave.ValidatorPaths;
        privateRPC: boolean;
        rpcBindAddress: string;
        rpcPort: number;
        tvuReceiveThreads: number;
        useSnapshotArchivesAtStartup: string;
        walRecoveryMode: string;
    }

    export interface ValidatorKeyPairs {
        identity: string;
        voteAccount: string;
    }

    export interface ValidatorPaths {
        accounts: string;
        ledger: string;
        log: string;
    }

}
