// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Svmkit.Agave.Outputs
{

    [OutputType]
    public sealed class KeyPairs
    {
        public readonly string Identity;
        public readonly string VoteAccount;

        [OutputConstructor]
        private KeyPairs(
            string identity,

            string voteAccount)
        {
            Identity = identity;
            VoteAccount = voteAccount;
        }
    }
}
