// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Svm.Agave.Outputs
{

    [OutputType]
    public sealed class ValidatorPaths
    {
        public readonly string Accounts;
        public readonly string Ledger;
        public readonly string Log;

        [OutputConstructor]
        private ValidatorPaths(
            string accounts,

            string ledger,

            string log)
        {
            Accounts = accounts;
            Ledger = ledger;
            Log = log;
        }
    }
}
