name: push
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.7
          cache-dependency-path: |
            **/*.sum
      - run: ./setup
      - run: make lint
      - run: make vet
      - run: make test
